#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

"$ROOT/check"

cp /home/sigvald/wrk/code/bin/app /var/www/image-server/bin
cp /home/sigvald/wrk/code/lib/CGI/Dispatch.pm /var/www/image-server/lib/CGI
cp /home/sigvald/wrk/code/lib/upload.pm /var/www/image-server/lib/
cp /home/sigvald/wrk/code/lib/serve.pm /var/www/image-server/lib/
cp /home/sigvald/wrk/code/lib/music.pm /var/www/image-server/lib/
cp /home/sigvald/wrk/code/templates/* /var/www/image-server/templates
mkdir -p /var/www/image-server/config
cp /home/sigvald/wrk/code/config/config.txt /var/www/image-server/config/
chown -R www-data:www-data /var/www/image-server/